package cv.dge.dge_api_intermed_lab.application.emprego.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

public record VagaResponse(
        Integer id,
        String codigoReferencia,
        String tipoOferta,
        String tipoOfertaDesc,
        String titulo,
        String descricao,
        LocalDate dataInicioCandidatura,
        LocalDate dataFimCandidatura,
        LocalDate dataInicioPrevisto,
        Integer duracaoContrato,
        String regimeContrato,
        Integer entidadeId,
        String denominacaoEntidade,
        String habilitacaoMinima,
        String nivelQualificacao,
        Integer numVagas,
        String habilitacaoMaxima,
        Object conhecimentoLinguistico,
        Object competenciasValorizadas,
        LocalTime horaInicio,
        LocalTime horaFim,
        Object diasSemana,
        Object cursosAreaFormacao,
        Object experienciaProfissional,
        String ilha,
        String ilhaDesc,
        String concelho,
        String concelhoDesc,
        String localOferta,
        Integer orientadorId,
        String orientadorDenominacao,
        Integer coordenadorId,
        String coordenadorDenominacao,
        String coordenadorEmail,
        String coordenadorTelefone,
        String emailContacto,
        String contacto,
        String observacao,
        String estado,
        String estadoDesc,
        Boolean editavel,
        LocalDateTime dateCreate,
        String userCreate,
        LocalDateTime dateUpdate,
        String userUpdate
) {
}
